include:
  - project: dhei/teams/pandora/gitlab-ci-templates
    file: products/gocomponents/GoComponent.Pipeline.gitlab-ci.yml
    ref: develop

variables:
  ARTIFACTORY_URL: $ARTIFACTORY_URL
  ARTIFACTORY_USERNAME: $ARTIFACTORY_USER
  ARTIFACTORY_KEY: $ARTIFACTORY_KEY
  CI: 'true'

  REPO_SERVER: artifactory
  REPO_DEPLOY: dhei-pandora-go
  REPO_RESOLVE: pandora-go-virtual

  HAZELCAST_HOST: docker
  HAZELCAST_IMAGE: dockerhub.devops.telekom.de/hazelcast/hazelcast
  HAZELCAST_TAG: 5.3.6

  DISABLE_BUILD_AND_PUBLISH: 'true'

stages:
  - prerequisite
  - test
  - scan
  - build-and-publish
  - post_test
  - publish

test:
  extends: .Templates:Golang:Application:Test
  stage: test
  variables:
    GO_TEST_TAGS: testing

publish:
  image: mtr.devops.telekom.de/tardis-internal/pandora/jfrog:1.1.0
  stage: publish
  only:
    refs:
      - tags
  before_script:
    - jf c add artifactory --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USERNAME --password $ARTIFACTORY_KEY
    - jf go-config --repo-resolve $REPO_RESOLVE --repo-deploy $REPO_DEPLOY --server-id-deploy $REPO_SERVER --server-id-resolve $REPO_SERVER
  script:
    - jf go-publish v$CI_COMMIT_TAG
